/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tela;

/**
 *
 * @author Welington
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bEmpresa = new javax.swing.JButton();
        bEmpregado = new javax.swing.JButton();
        bEmpresa1 = new javax.swing.JButton();
        bMensalidade = new javax.swing.JButton();
        bPlanoSaude = new javax.swing.JButton();

        bEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modulo_empresa.fw.png"))); // NOI18N
        bEmpresa.setToolTipText("Empresa");
        bEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmpresaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bEmpregado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modulo_empregado.fw.png"))); // NOI18N
        bEmpregado.setToolTipText("Empregado");
        bEmpregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmpregadoActionPerformed(evt);
            }
        });

        bEmpresa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modulo_empresa.fw.png"))); // NOI18N
        bEmpresa1.setToolTipText("Empresa");
        bEmpresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmpresa1ActionPerformed(evt);
            }
        });

        bMensalidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modulo_mensalidade.fw.png"))); // NOI18N
        bMensalidade.setToolTipText("Mensalidade");
        bMensalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMensalidadeActionPerformed(evt);
            }
        });

        bPlanoSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modulo_plano_saude.fw.png"))); // NOI18N
        bPlanoSaude.setToolTipText("Plano de Saúde");
        bPlanoSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlanoSaudeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bMensalidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bPlanoSaude))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bEmpresa1)
                        .addGap(128, 128, 128)
                        .addComponent(bEmpregado)))
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bEmpresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEmpregado, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPlanoSaude, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(727, 643));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bEmpregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmpregadoActionPerformed
        CadastroEmpregado t = new CadastroEmpregado();
        t.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bEmpregadoActionPerformed

    private void bEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmpresaActionPerformed
        CadastroEmpresa t = new CadastroEmpresa();
        t.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_bEmpresaActionPerformed

    private void bEmpresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmpresa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bEmpresa1ActionPerformed

    private void bMensalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMensalidadeActionPerformed
        CadastroEmpresa t = new CadastroEmpresa();
        t.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_bMensalidadeActionPerformed

    private void bPlanoSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlanoSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPlanoSaudeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEmpregado;
    private javax.swing.JButton bEmpresa;
    private javax.swing.JButton bEmpresa1;
    private javax.swing.JButton bMensalidade;
    private javax.swing.JButton bPlanoSaude;
    // End of variables declaration//GEN-END:variables
}
